---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: node_exporter
    run_list:
      - recipe[prometheus-client::node_exporter]
      - recipe[prometheus-client::haproxy_exporter]
    attributes:
  - name: haproxy_exporter
    run_list:
      - recipe[prometheus-client::haproxy_exporter]
    attributes:
