---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[prometheus-client::chef_handler]
      - recipe[prometheus-client::node_exporter]
      - recipe[prometheus-client::haproxy_exporter]
      - recipe[prometheus-client::consul_exporter]
      - recipe[prometheus-client::elasticsearch_exporter]
    attributes: